add menu and fix compiler warnings
bartekpacia/snake pull request #2
Opened 2022-05-26 12:26 UTC by H4wk507

dodałem menu i zamieniłem sf::Vector2i na sf::Vector2u, żeby nie wywalało ostrzeżeń kompilatora

2022-05-26 12:56 UTC, bartekpacia requested changes

2022-05-26 12:56 UTC, bartekpacia commented on src/menu.cpp
> +                  window);
❤️

2022-05-26 12:56 UTC, bartekpacia commented on src/menu.cpp
> +                         height / (numberOfOptions + 1) * (i + 1)));
weź to daj do 2 zmiennych

2022-05-26 12:56 UTC, bartekpacia commented on src/menu.cpp
> +void Menu::MoveUp() {
`move_up`

2022-05-26 12:56 UTC, bartekpacia commented on src/menu.cpp
> +void Menu::MoveDown() {
`move_down`

2022-05-26 12:56 UTC, bartekpacia commented on src/game.cpp
> +                            }
weź to wyjeb do jakiejś metody prywatnej bo duże się robi

2022-05-26 12:56 UTC, bartekpacia commented on src/game.cpp
> +        window_.clear(sf::Color(1, 3, 50));
ten kolor daj do jakiejś stałej i nazwij (nie wiadomo co to jest za kolor na pierwszy rzut oka)

2022-05-26 12:56 UTC, bartekpacia commented on src/game.cpp
> +    open_menu();
ten `game.cpp` to jest totalny syf, będziemy musieli to przepisać i zmodularyzować jakoś bo ugrzęźniemy w tym bagnie

ale na razie git

2022-05-26 12:56 UTC, bartekpacia commented on include/menu.h
> +    Options getPressedItem() const {
`get_pressed_item` (albo `get_selected_option`, żeby było spójnie)

a najlepiej: `get_selected_action`

2022-05-26 12:56 UTC, bartekpacia commented on include/menu.h
> +    };
rename to `Action`

2022-05-26 12:56 UTC, bartekpacia commented on include/menu.h
> +    size_t selectedOptionIndex{0};
`size_t selected_action_index = 0`

Jeśli chcemy używać _uniform initialization syntax_, to używajmy jej wszędzie, albo nigdzie. Na razie pójdźmy drogą "(prawie)nigdzie", a potem najwyzej w jakimś 1 PRku sie wszystko zmieni na _uniform init_

2022-05-26 12:56 UTC, bartekpacia commented on include/menu.h
> +    size_t numberOfOptions{3};
rename to `action_count`

2022-05-26 12:57 UTC, bartekpacia commented
jakiego środowiska i kompilatora używasz? @H4wk507

2022-05-26 17:48 UTC, H4wk507 commented
> jakiego środowiska i kompilatora używasz? @H4wk507

vscode i kompilator ten co w makefile czyli g++ tylko mam clang-tidy włączone

2022-05-26 18:07 UTC, bartekpacia commented
spoko

musimy config `clang-tidy` zacommitować do repo

2022-05-27 12:15 UTC, bartekpacia approved these changes
gicior

merguj

2022-05-27 12:57 UTC, H4wk507 commented
> gicior
> 
> merguj

nie mam uprawnień xd @bartekpacia

2022-05-27 12:58 UTC, merged

2022-05-27 12:59 UTC, bartekpacia commented
xD sory

jak wrócę do domu to ci dam